# 文件存储路径（根据系统调整）
file:
  upload-dir: ./files
spring:
  web:
    resources:
      static-locations: classpath:/static,classpath:/dist,file:./files
  resources:
    static-locations: classpath:/static,classpath:/dist,file:./files
  servlet:
    multipart:
      max-file-size: 10MB  # 单文件大小限制

server:
  host: http://127.0.0.1
  port: 82

logging:
  pattern:
    console: "%clr([%thread]){blue} %clr(%-32.32logger{32}){magenta} %clr(%d{yyyy-MM-dd HH:mm:ss}){red} %clr(%-5p): %msg%n"
    file: "[%thread] %-32.32logger{32} %d{yyyy-MM-dd HH:mm:ss} %-5p: %msg%n"
  file:
    # 输出的log文件名
    name: ./logs/slf4j.log
    # 输出的文件的路径
    path: logs
    # 限制日志文件的大小
    max-size: 10MB
    # 日志的保存天数
    max-history: 7